FROM ruby:3.2.2

WORKDIR /my_tokyo
COPY Gemfile /my_tokyo/Gemfile
COPY Gemfile.lock /my_tokyo/Gemfile.lock
RUN bundle install

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]