# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: my_tokyo_development

test:
  <<: *default
  database: my_tokyo_test

production:
  <<: *default
  database: my_tokyo_production
  username: my_tokyo
  password: <%= ENV["MY_TOKYO_DATABASE_PASSWORD"] %>
